### ISSUE TITLE
The Chilean Government decided to delay the DST start from September 4 to September 11, in order to "avoid problems in election day" (we do held a plebiscite on September 4th).

### ISSUE THREAD

**Issue by BoylikeA12** [git-lfs/lfs-test-server#106]
The Chilean Government decided to delay the DST start from September 4 to September 11, in order to "avoid problems in election day" (we do held a plebiscite on September 4th).

Because of that, tzdata2022b was released (and now 2022c, that fixes a build-time issue). This update is critical for users that depend on having the correct time at the moment.

As I see with #576, the last couple of times this have happened, it was handled with relative quick, getting the updated the data from the icu-data repo (there is even a PR to do it automatically at nodejs/node#43988). As of now, icu-data has an open PR to update this at unicode-org/icu-data#28, and right now the data can be copied from the PR, but it should be accepted soon anyway.

Sadly, I see that the last LTS update was released just today (16.17.0). As i think this could be a critical issue, would it be possible to do a point-release in the following weeks to handle this, so it can be picked by downstream-distributions (AWS Lambda in my case)

Thanks.

__Originally posted by @Manizuca in https://github.com/nodejs/Release/issues/773__

**Comment by bk2204** [comment]
This doesn't seem to be related to Git LFS, so I'm closing it.
