### ISSUE TITLE
tusd binary versus importing ?

### ISSUE THREAD

**Issue by gedw99** [git-lfs/lfs-test-server#115]
https://github.com/tus/tusd/blob/main/docs/usage-package.md

Did you use the binary as a sort of API drift protection ?

**Comment by chrisd8088** [comment]
This feature was implemented quite a while ago, in PR #52 in 2016, and none of the current Git LFS core team were involved at that time, so we can't speak from personal experience.

However, that PR has a conveniently thorough description, which I think fully explains the implementation choice:

> I couldn't create meaningful tests for this without making the project dependent on the tus codebase, which is quite large (recursive dependencies). This is also the reason I chose to implement it by calling the `tusd` binary (which the user must have installed when opting in), rather than directly referencing the tus code - that would have been more elegant and wouldn't have had to assume knowledge of the tusd storage model, but it would have bloated the vendor directory horribly so I consider this the lesser of the two evils.
