### ISSUE TITLE
How to you set it up

### ISSUE THREAD

**Issue by kemin711** [git-lfs/lfs-test-server#119]
I have followed the instruction, and able to start the server.  When testing from the client side, it ask me for username and password.  How do I configure that.  I have http running on the server side.  I have created htpasswd on the server side, that does not seem to work.

**Comment by chrisd8088** [comment]
If you start the server with `LFS_ADMINUSER=admin LFS_ADMINPASS=<password> ./lfs-test-server` and then log into it at something like `http://localhost:8080/mgmt` using that `admin` user and password, you can click on the "Users" tab in the simple management UI and add users to the local database.

![Image](https://github.com/git-lfs/lfs-test-server/assets/28857117/d4731425-3df5-4fd1-8459-4fcb47983cde)

Those should be the user names and password you then want to provide with the Git and Git LFS clients.

**Comment by kemin711** [comment]
I am able to set up the lfs for my local git with https.  Maybe should update the documentation to help others.  It is a good learning experience for me.

**Comment by kemin711** [comment]
After some testing, I am still getting errors:

```
kzhou@joyclock ~/tmp/testlfs$ git pull
Already up to date.
kzhou@joyclock ~/tmp/testlfs$ git lfs pull
[eb9e5055e63562bcb69109ccf8a39240bc77e8a54b0e005b98b6eea7549415b4] Not found: [404] Not found                                                                              
[ddf9e9e79f52e00e6c29c265c76437621a0849a79373d4f1e216b18ce384ce03] Not found: [404] Not found
Failed to fetch some objects from 'https://10.10.0.150:8090'
```
How was the user name and password used.  It dis not ask for anything because I am a regular user with the same username on both the server and the client computer.

**Comment by kemin711** [comment]
Quick question: when you try to clone, pull, and push from the some computer locally to the lfs hosted on the same computer, how do you set it up?  Do you set up a config using local host?
