### ISSUE TITLE
What is missing to make this server production ready?

### ISSUE THREAD

**Issue by green-coder** [git-lfs/lfs-test-server#54]
The documentation says that the server is not production ready but doesn't explain why.
If people want to contribute to make it production ready, what do they need to look at?

**Comment by Noiwex** [comment]
where the hell is response @ttaylorr @technoweenie

**Comment by technoweenie** [comment]
This repository is purely a test implementation of the server API. There are no plans to make this production ready. I would say the main thing it's missing is stable clustered file storage, and a team dedicated to implementing and maintaining it.

**Comment by Noiwex** [comment]
So LFS is made with intention to offer paid LFS storage plans on github? What a shame.
