### ISSUE TITLE
Cleaning Up

### ISSUE THREAD

**Issue by Gfurst** [git-lfs/lfs-test-server#57]
So how would one go cleaning up this test server?

Is it just a question of remove the db and related objects and firing up the daemon, pushing up again to the server?

**Comment by ttaylorr** [comment]
@Gfurst, that sounds reasonable, but @rubyist would know better.

**Comment by Gfurst** [comment]
Any news about this? would manually removing local files work? (eg remove everything then push again from know repos that you have the objects)

**Comment by ttaylorr** [comment]
> would manually removing local files work?

Yes, this should work -- and sorry for the 📻 silence on this! This server is not a currently-maintained project, and is intended to serve as a reference implementation of the Git LFS API specification, not for production use.
