### ISSUE TITLE
File Locking API

### ISSUE THREAD

**Issue by tux21b** [git-lfs/lfs-test-server#58]
It would be great if this projects would also support the git file locking API:
https://github.com/git-lfs/git-lfs/blob/master/docs/api/locking.md

**Comment by ttaylorr** [comment]
Hi @tux21b, thanks for opening this. I definitely agree that this project should support the file locking API, but this isn't currently on my roadmap.

That being said, I'd be happy to help anyone who wants to contribute through a pull request. There is a rough reference implementation in the [Git server that LFS uses during integration tests][1] that may be a useful starting place.

[1]: https://github.com/git-lfs/git-lfs/blob/master/test/cmd/lfstest-gitserver.go#L849-L1150
