### ISSUE TITLE
permissions

### ISSUE THREAD

**Issue by dfroger** [git-lfs/lfs-test-server#59]
How can I create user with read+write permissions, and user with read-only permissions?

If not possible, is there any workaround?

Does it mean the `lfs-test-server` can be used only privately, isn't it possible to set up a public lfs server?

**Comment by technoweenie** [comment]
This server isn't meant for production use, it's only meant to be a local implementation of the LFS API for testing. Feel free to fork it if you want to use it publicly though.

**Comment by dfroger** [comment]
Ok, thanks for your reply.
