### ISSUE TITLE
exec format error

### ISSUE THREAD

**Issue by tomitrescak** [git-lfs/lfs-test-server#70]
Hi, I am not sure what I am doing wrong, but when I unpack the file and run it (tried Mac version as well as Linux) they both give "exec format error". What am I missing here?

**Comment by technoweenie** [comment]
What OS and cpu arch are you on? This could happen if you're on Windows, or on an arm cpu (like raspberry pi).

**Comment by tomitrescak** [comment]
I'm on Mac. But no worries, got it running via GO. Thanks!
