### ISSUE TITLE
can remove boltdb to mysql ?

### ISSUE THREAD

**Issue by Neeke** [git-lfs/lfs-test-server#72]

**Comment by technoweenie** [comment]
This is a test server, so having something dead simple to run locally is very important. You're welcome to use this project as a base for your own mysql-backed LFS server though.

**Comment by ttaylorr** [comment]
> You're welcome to use this project as a base for your own mysql-backed LFS server though.

Agreed. Since I don't think that this issue will result in any changes to `lfs-test-server`, I'm going to close this issue for now.
