### ISSUE TITLE
First push fails but second succeeds with large files and lfs-test-server

### ISSUE THREAD

**Issue by aggieNick02** [git-lfs/lfs-test-server#80]
We have a project that needs to track large (>4GB) files so we spun up a little lfs-test-server on ubuntu18.04 LTS to go along with our repo on github.com. We're on the latest lfs-test-server (built from source) and latest git for windows. We started testing some things out with a dummy repo.

We're using the workaround of skipping smudge to work with these files on windows. It seems to work pretty well most of the time. But a few minutes ago I ran `git push` after a commit with a new big file, and got this output:

> `Uploading LFS objects:   0% (0/1), 9.1 GB | 104 MB/s, done
> Fatal error: Server error: http://10.100.0.1:9999/objects/2400552958e23519156f20f3256b49bc572cd9d728ef50a8d93702d886813ab8
> error: failed to push some refs to 'git@github.com:aggieNick02/hello-world.git`

I checked the lfs-test-server's file store and the entire new file, with correct contents, was present (sha256 matched). The log for lfs-test-server showed no errors:

> `2018-12-06T20:18:08Z bmaster-dev lfs[17919] [server.go:342]: method=POST url=/objects/batch status=200 request_id=7448c73b-a8c8-e706-004b-f0c387c7b411
> 2018-12-06T20:18:08Z bmaster-dev lfs[17919] [server.go:342]: method=POST url=/objects/batch status=200 request_id=8324022a-491a-ab35-91ef-696d3b650979
> 2018-12-06T20:18:08Z bmaster-dev lfs[17919] [server.go:342]: url=/objects/batch status=200 request_id=f1cb516f-58bc-da0c-6c9c-18cd50faed95 method=POST
> 2018-12-06T20:18:08Z bmaster-dev lfs[17919] [server.go:342]: method=POST url=/objects/batch status=200 request_id=61caa3ad-87f8-4322-d697-8dcf248e71bd
> 2018-12-06T20:18:08Z bmaster-dev lfs[17919] [server.go:342]: method=POST url=/objects/batch status=200 request_id=053b138a-4d0f-a740-5968-bfa3391d7687
> 2018-12-06T20:18:08Z bmaster-dev lfs[17919] [server.go:342]: request_id=68dac289-c26f-41db-76b0-6c18f6ad0d65 method=POST url=/objects/batch status=200
> 2018-12-06T20:18:08Z bmaster-dev lfs[17919] [server.go:342]: method=POST url=/objects/batch status=200 request_id=f37540e9-2710-b812-43c8-eda61ebfac91
> 2018-12-06T20:18:08Z bmaster-dev lfs[17919] [server.go:342]: method=POST url=/objects/batch status=200 request_id=fc16bd86-5627-0d33-1309-389fef6457af
> 2018-12-06T20:18:11Z bmaster-dev lfs[17919] [server.go:361]: url=/objects/2400552958e23519156f20f3256b49bc572cd9d728ef50a8d93702d886813ab8 status=200 request_id=67556744-5757-00ab-aaf9-22de77eff880 method=PUT`

At a loss, I ran `git push` again. This time, success. (The only thing worse than failure, because now it's an intermittent issue. ;-) ) Also bizarre was that the output showed uploading twice the size of the new file:

> `$ git push
> Uploading LFS objects: 100% (1/1), 18 GB | 104 MB/s, done
> Enumerating objects: 6, done.
> Counting objects: 100% (6/6), done.
> Delta compression using up to 8 threads
> Compressing objects: 100% (4/4), done.
> Writing objects: 100% (4/4), 514 bytes | 257.00 KiB/s, done.
> Total 4 (delta 1), reused 0 (delta 0)
> remote: Resolving deltas: 100% (1/1), completed with 1 local object.
> To github.com:aggieNick02/hello-world.git
>    de87404..b617ba8  master -> master`

If I repeat this whole sequence (new big file, add and commit, push, push), I get the same results. First push fails, second one succeeds with double the upload size... any ideas what's going on?

**Comment by aggieNick02** [comment]
Great, thanks for moving it for me and the info. I'll be digging into lfs-test-server. I think there is probably significant underestimated demand for better versioning of large files, and the lfs-test-server running locally is an attractive and obvious answer. Granted, if it doesn't actually work, I guess it's not such a great answer ;-)

**Comment by bk2204** [comment]
I think the most important thing to look into is what error message you're getting back from the server. That will probably tell us a lot about what problem is occurring server side.

It may be helpful to try `GIT_TRANSFER_TRACE=1` if you haven't already. That's turned on automatically by `GIT_CURL_VERBOSE` in newer versions (I think 2.6.0 and newer), but not in older versions, which don't know about `GIT_CURL_VERBOSE`.

**Comment by bk2204** [comment]
I believe you'd probably want to instrument https://github.com/git-lfs/lfs-test-server/blob/master/server.go#L357 and have it print the error message it's producing to standard error. That would look like so (you'll need to import `os` at the top):

```
fmt.Fprintf(os.Stderr, `{"message":"%s"}`, err)
```

If you can determine what that error message is, that would tell you where the problem is occurring.

**Comment by aggieNick02** [comment]
Great, thanks. An interesting tidbit on the server side now is that it prints out each request and status. It thinks all of them are succeeding. There are a lot of bunched object /objects/batch requests after the PUT. But the logs show status=200 on the server side. Will see what I can get with the instrumentation you suggested.
Also, I tried both `lfs.concurrenttransfers=1` and `lfs.basictransfersonly=1` just on some wild hunches, but no change in results.

**Comment by aggieNick02** [comment]
So the PutHandler is exiting normally. So the reason for the failed connection is somewhere else. I'll keep digging. I'm also on a super old version of go (18.04LTS by default gets you 1.6.2) so I'll probably update that to the latest for good measure first.

**Comment by bk2204** [comment]
I don't know if you intended to write "18.04" or "16.04",  but 18.04 does have the `golang-1.10` package, which should be sufficient to build and test the LFS server. It should also be present in `xenial-backports`, if you're using 16.04.

**Comment by aggieNick02** [comment]
Oops, sorry about that. 16.04. I'll grab the backport.

**Comment by aggieNick02** [comment]
Getting closer. When an LFS push is normal and succeeds on the first time, the sequence of events is:

> Client: Batch Operation Request to get URL for uploading file
> Server: Batch Operation Response with upload URL
> Client: PUT Request to upload URL
> Server: PUT Response

When the LFS push is for a big file that fails, the sequence is:

> Client: Batch Operation Request to get URL for uploading file
> Server: Batch Operation Response with upload URL
> Client: PUT Request to upload URL
> Client: Batch Operation Request to get URL for uploading file
> Server: Batch Operation Response with upload URL
> Client: PUT Request to upload URL (which fails)

So for some reason, git-lfs issues multiple BatchOperation requests to upload the file if the upload of the file takes "too long", and repeatedly tries to upload it again and fails. When the second push succeeds, the client/server messaging is the same until the second batch operation request to get URL for uploading file; at that point, the response actually contains a download URL and no upload URL, so a second PUT does not occur.

I'll keep digging, but even if this is an lfs-test-server issue, it seems bizarre that the git-lfs client issues all of these BatchOperation requests to try to upload the file again *BEFORE* the response for the initial PUT is even received.

**Comment by bk2204** [comment]
When an upload fails, it can be for a number of reasons, one of which is that the authentication credentials expired. When we retry a request, we issue a new batch request, which will provide us with a new set of credentials if required. (Even if the reason wasn't that the credentials expired, they might expire soon, and we'd want fresh ones to maximize our success potential.)

We do this asynchronously (in a goroutine), so there's probably some reason that we're finding the initial PUT request is failing, perhaps a timeout of some sort.

**Comment by aggieNick02** [comment]
Got it, thanks. So turning the retries down to 1 with lfs.transfer.maxretries=1 eliminated a lot of the noise and makes things a bit clearer. Just like you said, the PUT request is failing for some reason. The lfs-test-server thinks it has succeeded from its side of logging, but the client shows no response from the initial put request (the 500 errors are for the subsequent put attempts).

Whatever the failure is, it is at the very end. When the second push succeeds, it is quite wonky. There is no response listed on the client side to the PUT, but the subsequent batch operation doesn't result in another put attempt, so there is no error message... I think I'm going to put wireshark between the two and try to get a clearer picture of who is in the wrong.

**Comment by aggieNick02** [comment]
Got wireshark going and understand the problem now.

At about 90 seconds, the last bytes of the file are sent from the client. At 120 seconds, the BatchRequest is sent, and at 150 seconds, the response to the PUT is sent, but the client is no longer listening for it.

There is a delay between when the last file bytes are sent and when the lfs-server has fully processed them and placed the file on disk and a response is sent. For our lfs-test-server, the lfs storage is on a spinning-disk NAS. When all is said and done, this delay is about 60 seconds for our 9GB file.

This is longer than the default lfs.activitytimeout of 30 seconds. Bumping it to 120 resolves the problem for the 9GB file. Setting to 0 (unlimited) would resolve for any size.

I'll look into Monday if there is anything simple that could be done in the lfs-test-server to avoid the long delay where no network traffic is present.

**Comment by bk2204** [comment]
Yeah, that makes a lot of sense. We're probably timing out due to the close, which we need to be sure to do so that it's on disk properly. I don't know of anything that we could do differently, but if you think of anything, I'm definitely open to suggestions.

**Comment by aggieNick02** [comment]
Was typing up my findings when you responded with what I would find. :-)

Spent a bit of time investigating this, and I'm not sure there is a better solution than turning the timeout up or to 0. The big hang with no network activity between the lfs client and server is indeed on the file close. The close has to happen, and there's no easy way to get around it. I could artificially throttle the file write (knowing that it is to a NAS) which would decrease the time the close takes, but there's not a generic way to do that that would make sense for lfs-test-server users. Maybe there are things on my NAS that I could tweak to have it slow uploads to it down to a rate it can keep up with better.

I think there's enough here to close as not a bug. For our use case, I'll think about whether a NAS for a content store makes sense.

Thanks @bk2204 for all the help troubleshooting and debugging this. Really appreciated. :-)

**Comment by bk2204** [comment]
You're very welcome. I'm glad we got to the bottom of your problem, even if it wasn't as easily solved as I'd hoped.

**Comment by aggieNick02** [comment]
I'm sure a lot of that had to do with my newness to both go and the lfs-test-server more than anything else. Now I'm better prepared. :-)

**Comment by Neytoooo** [comment]
PS C:\laragon\www\dev-extranet> git push -u origin master
Uploading LFS objects: 100% (8/8), 639 MB | 0 B/s, done.
Enumerating objects: 11160, done.
Counting objects: 100% (11160/11160), done.
Delta compression using up to 4 threads    
Compressing objects: 100% (9175/9175), done.
error: RPC failed; HTTP 500 curl 22 The requested URL returned error: 500
send-pack: unexpected disconnect while reading sideband packet
Writing objects: 100% (11160/11160), 2.48 GiB | 11.01 MiB/s, done.
Total 11160 (delta 1872), reused 10956 (delta 1668), pack-reused 0
fatal: the remote end hung up unexpectedly
Everything up-to-date
PS C:\laragon\www\dev-extranet> 


bonjour j'ai eu cette erreur je ne sais pas comment faire pour le régler a mon avis ça dois venir de la taille des fichiers mais comment faire ?

**Comment by bk2204** [comment]
Bonjour,

Je pense que l'erreur est à cause du code 500 (Erreur Internale de Serveur) reçu du serveur de Git.  Il n'a rien à voir avec le projet Git LFS, mais j'essayerai de vous aider un peu quand même.  Si vous utilisez GitHub pour vos codes, il y a une limite de 2 Go (2 GB) et vous ne pouvez pas televerser un paquet qui est plus gros que cela.  Vous pouvez televerser en petits morceaux [avec un script come cela](https://stackoverflow.com/questions/67851587/github-send-git-objects-incrementally-or-in-separate-batches).

Si vous avez plus de questions, je vous conseiller de contacter le service clientèle de GitHub.

---

Hello,

I believe the error is due to the code 500 (Internal Server Error) received from the Git server.  This has nothing to do with the Git LFS project, but I'll try to help you a bit nonetheless.  If you use GitHub for your code, there's a limit of 2 GB and you can't push a pack which is larger than that.  You can push in small chunks [with a script like this one]((https://stackoverflow.com/questions/67851587/github-send-git-objects-incrementally-or-in-separate-batches)).

If you have more questions, I'd advise you to contact GitHub support.

**Comment by Neytoooo** [comment]
merci beaucoup !
