### ISSUE TITLE
verbose logging

### ISSUE THREAD

**Issue by axkibe** [git-lfs/lfs-test-server#99]
How do I turn this on?
(I just want to see the json replies for example to the batch API on an upload request so I can properly implement the LFS API, the docs aren't too much helpful on this either)

**Comment by chrisd8088** [comment]
I don't think there is any, at a quick look.  I would try just adding `logger.Log()` [calls](https://github.com/git-lfs/lfs-test-server/blob/74a6f6dd62b093ad266097be49e118030f5fe827/server.go#L686) wherever you need them to extract the data you're looking for.
